#!/usr/bin/env node
// ---------------------------------------------------------------------------
// generate-schema.mjs
// Reverse-engineers the Base44 backend into portable Postgres DDL.
//
// Reads every entity blueprint in ./entities-full/*.json and emits:
//   • CREATE TABLE with typed columns (+ Base44's implicit system columns)
//   • ALTER TABLE ... ENABLE ROW LEVEL SECURITY
//   • CREATE POLICY per operation (select/insert/update/delete), translated
//     faithfully from each entity's `rls` block.
//
// Auth is abstracted behind two helper functions so this SQL runs on ANY
// Postgres and adapts to whatever auth we bolt on (Supabase, custom, etc.):
//   • app_current_email()  -> text     (the signed-in user's email)
//   • app_is_admin()       -> boolean  (is that user an admin)
//   • app_current_uid()    -> text     (the signed-in user's id)
//
// Output: ./schema.sql   (run:  node generate-schema.mjs)
// ---------------------------------------------------------------------------
import { readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ENTITIES_DIR = join(__dirname, 'entities-full');
const OUT = join(__dirname, 'schema.sql');

// ── camelCase / PascalCase entity name -> snake_case table name ─────────────
function toSnake(name) {
  return name
    .replace(/([a-z0-9])([A-Z])/g, '$1_$2')
    .replace(/([A-Z]+)([A-Z][a-z])/g, '$1_$2')
    .replace(/[\s-]+/g, '_')
    .toLowerCase();
}

// ── JSON-schema property -> Postgres column type ────────────────────────────
function pgType(prop) {
  const t = Array.isArray(prop?.type) ? prop.type.find((x) => x !== 'null') : prop?.type;
  switch (t) {
    case 'string':  return 'text';
    case 'number':  return 'double precision';
    case 'integer': return 'bigint';
    case 'boolean': return 'boolean';
    case 'array':   return 'jsonb';
    case 'object':  return 'jsonb';
    default:        return 'text';
  }
}

function sqlLiteral(v) {
  if (v === null || v === undefined) return 'NULL';
  if (typeof v === 'boolean') return v ? 'true' : 'false';
  if (typeof v === 'number') return String(v);
  if (typeof v === 'object') return `'${JSON.stringify(v).replace(/'/g, "''")}'::jsonb`;
  return `'${String(v).replace(/'/g, "''")}'`;
}

// Base44 stamps these on every record implicitly. We materialize them so RLS
// and the drop-in client behave identically to the hosted backend.
const SYSTEM_COLUMNS = new Set(['id', 'created_date', 'updated_date', 'created_by', 'created_by_id']);

// ── Translate one RLS condition object into a SQL boolean expression ─────────
// Handles: {}, {$or:[...]}, {$and:[...]}, {user_condition:{role:'admin'}},
// {field:'{{user.email}}'|'{{user.id}}'|literal}, and dotted jsonb paths
// ("data.user_email" -> data->>'user_email"). Multiple keys in one object AND.
function lhs(field) {
  if (field.includes('.')) {
    const [col, ...rest] = field.split('.');
    return `(${col} ->> '${rest.join('.')}')`;
  }
  return field;
}

function translateCond(cond) {
  if (cond == null || (typeof cond === 'object' && Object.keys(cond).length === 0)) {
    return 'true'; // empty rule = unrestricted (Base44 semantics for read: {})
  }
  const parts = [];
  for (const [key, val] of Object.entries(cond)) {
    if (key === '$or') {
      parts.push('(' + val.map(translateCond).join(' OR ') + ')');
    } else if (key === '$and') {
      parts.push('(' + val.map(translateCond).join(' AND ') + ')');
    } else if (key === 'user_condition') {
      if (val?.role === 'admin') parts.push('app_is_admin()');
      else parts.push('true');
    } else if (val === '{{user.email}}') {
      parts.push(`${lhs(key)} = app_current_email()`);
    } else if (val === '{{user.id}}') {
      parts.push(`${lhs(key)} = app_current_uid()`);
    } else {
      parts.push(`${lhs(key)} = ${sqlLiteral(val)}`);
    }
  }
  return parts.length > 1 ? '(' + parts.join(' AND ') + ')' : parts[0];
}

// ── Build the full SQL document ─────────────────────────────────────────────
const header = `-- ===========================================================================
-- CYBERNETIC's / ERU — backend schema, reverse-engineered from Base44
-- Generated by MIGRATION/generate-schema.mjs — DO NOT edit by hand.
-- Portable Postgres. Define the three app_* helpers for your chosen auth,
-- then run this file to stand up the whole data model with security intact.
-- ===========================================================================

-- Auth abstraction — reimplement these for the backend you land on.
-- (Supabase example shown; swap the bodies, keep the signatures.)
create or replace function app_current_email() returns text language sql stable as $$
  select nullif(current_setting('request.jwt.claims', true)::jsonb ->> 'email', '')
$$;
create or replace function app_current_uid() returns text language sql stable as $$
  select nullif(current_setting('request.jwt.claims', true)::jsonb ->> 'sub', '')
$$;
create or replace function app_is_admin() returns boolean language sql stable as $$
  select coalesce((current_setting('request.jwt.claims', true)::jsonb ->> 'role') = 'admin', false)
$$;
`;

const files = readdirSync(ENTITIES_DIR).filter((f) => f.endsWith('.json')).sort();
const blocks = [];
let tableCount = 0;
let policyCount = 0;

for (const file of files) {
  const entity = JSON.parse(readFileSync(join(ENTITIES_DIR, file), 'utf8'));
  const entityName = file.replace(/\.json$/, '');
  const table = toSnake(entityName);
  const props = entity.properties || {};
  const required = new Set(entity.required || []);

  const cols = [
    'id uuid primary key default gen_random_uuid()',
    'created_date timestamptz not null default now()',
    'updated_date timestamptz not null default now()',
    'created_by text',
    'created_by_id text',
  ];

  for (const [name, prop] of Object.entries(props)) {
    if (SYSTEM_COLUMNS.has(name)) continue; // don't double-define system cols
    const col = toSnake(name) === name ? name : name; // keep original field name (client relies on it)
    let line = `"${name}" ${pgType(prop)}`;
    if (prop && Object.prototype.hasOwnProperty.call(prop, 'default')) {
      line += ` default ${sqlLiteral(prop.default)}`;
    }
    if (required.has(name)) line += ' not null';
    cols.push(line);
  }

  let block = `-- ─── ${entityName} → ${table} ${'─'.repeat(Math.max(0, 46 - table.length))}\n`;
  block += `create table if not exists "${table}" (\n  ${cols.join(',\n  ')}\n);\n`;
  block += `alter table "${table}" enable row level security;\n`;

  // RLS → policies. Map Base44 ops to Postgres policy commands.
  const rls = entity.rls || {};
  const opMap = { read: 'select', create: 'insert', update: 'update', delete: 'delete' };
  for (const [op, cmd] of Object.entries(opMap)) {
    if (!(op in rls)) continue;
    const expr = translateCond(rls[op]);
    const pol = `${table}_${op}`;
    if (cmd === 'insert') {
      block += `create policy "${pol}" on "${table}" for insert with check (${expr});\n`;
    } else {
      block += `create policy "${pol}" on "${table}" for ${cmd} using (${expr});\n`;
    }
    policyCount++;
  }

  blocks.push(block);
  tableCount++;
}

const sql = header + '\n' + blocks.join('\n');
writeFileSync(OUT, sql);
console.log(`✓ Wrote ${OUT}`);
console.log(`  ${tableCount} tables, ${policyCount} RLS policies from ${files.length} entities`);
